apiVersion: v1
kind: Namespace
metadata:
  name: nushungry
  labels:
    name: nushungry
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: nushungry-dev
  labels:
    name: nushungry-dev
    environment: development
